### ISSUE TITLE
double check ALL mappings for concatenation delimeters

### ISSUE THREAD

**Issue by followfung** [ryersonlibrary/minisis_xml_to_csv#11]
With #8, the description mappings should be to be identical to the way @mjsuhonos did accessions and authorities mappings. Need to check over it to make sure that the delimiters are the right ones.

**Comment by followfung** [comment]
We should actually go through everything and check that they have the right delimeters. Pipes are for fields that get split into multiple relations, otherwise newlines should probably be default.

**Comment by mjsuhonos** [comment]
I'm marking this done as per recent commits.
